<?php

namespace AppBundle\Repository;

/**
 * rendezvousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rendezvousRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAction($user)
    {

        return $this->createQueryBuilder()
            ->select( 'rendezvous' )
            ->from( 'AppBundle:rendezvous', 'rendezvous' )
            ->where( 'rendezvous.user = : id' )

            ->setParameter('id', $user)
            ->getQuery()
            ->getResult
            ;


    }



}
