<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'captcha.type' shared service.

return $this->services['captcha.type'] = new \Gregwar\CaptchaBundle\Type\CaptchaType(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'}, ${($_ = isset($this->services['gregwar_captcha.generator']) ? $this->services['gregwar_captcha.generator'] : $this->load('getGregwarCaptcha_GeneratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, $this->getParameter('gregwar_captcha.config'));
