<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'gregwar_captcha.generator' shared service.

return $this->services['gregwar_captcha.generator'] = new \Gregwar\CaptchaBundle\Generator\CaptchaGenerator(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['gregwar_captcha.captcha_builder']) ? $this->services['gregwar_captcha.captcha_builder'] : ($this->services['gregwar_captcha.captcha_builder'] = new \Gregwar\Captcha\CaptchaBuilder())) && false ?: '_'}, ${($_ = isset($this->services['gregwar_captcha.phrase_builder']) ? $this->services['gregwar_captcha.phrase_builder'] : ($this->services['gregwar_captcha.phrase_builder'] = new \Gregwar\Captcha\PhraseBuilder())) && false ?: '_'}, ${($_ = isset($this->services['gregwar_captcha.image_file_handler']) ? $this->services['gregwar_captcha.image_file_handler'] : $this->load('getGregwarCaptcha_ImageFileHandlerService.php')) && false ?: '_'});
