<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxilkx0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxilkx0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXxilkx0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXxilkx0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXxilkx0\appDevDebugProjectContainer([
    'container.build_hash' => 'Xxilkx0',
    'container.build_id' => '21a9b87d',
    'container.build_time' => 1581599048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxilkx0');
